#
# installation
#

- name: Install tendrl-ceph-integration
  yum:
    name=tendrl-ceph-integration
    state=latest
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

#
# post installation configuration
#

# as documented in installation.rst
# workaround for https://github.com/Tendrl/ceph_integration/issues/57
- name: Specify log_cfg_path in tendrl.conf
  ini_file:
    dest=/etc/tendrl/tendrl.conf
    section=ceph_integration
    option=log_cfg_path
    value="/etc/tendrl/ceph_integration_logging.yaml"

- name: Start and enable tendrl-ceph-integration service
  service:
    name=tendrl-cephd
    state=started
    enabled=yes
