- name: Install GlusterFS
  yum:
    name="{{ item }}"
    disable_gpg_check=yes
    state=latest
  with_items:
    - glusterfs
    - glusterfs-fuse
    - glusterfs-server
    - python-gluster
    - glusterfs-rdma
#    - glusterfs-debuginfo
    - glusterfs-api
    - glusterfs-client
    - glusterfs-api-devel
    - glusterfs-devel
    - glusterfs-libs
    - userspace-rcu
    - glusterfs-cli
    - glusterfs-events
    - glusterfs-rdma
    - glusterfs-client-xlators
    - glusterfs-extra-xlators
    - glusterfs-geo-replication
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Run glusterd service
  service:
    name=glusterd
    state=started
