- name: Install GlusterFS Server
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-server
    - glusterfs-geo-replication
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Run and enable glusterd service
  service:
    name=glusterd
    state=started
    enabled=yes
