#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

# according to https://github.com/Tendrl/node-agent/blob/master/doc/source/installation.rst
- name: Specify etcd_connection in node-agent.conf.yaml
  lineinfile:
    dest=/etc/tendrl/node-agent/node-agent.conf.yaml
    regexp='^etcd_connection:*'
    line="etcd_connection{{ ':' }} {{ groups['usm_server'][0] }}"

- name: Add provisioner/gluster tag in node-agent.conf.yaml (on gluster nodes)
  lineinfile:
    dest=/etc/tendrl/node-agent/node-agent.conf.yaml
    insertafter='^tags:$'
    line="  - provisioner/gluster"
  when: "'gluster' in group_names"

# https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.2.2
- name: Add provisioner/ceph tag in node-agent.conf.yaml (on tendrl-server)
  lineinfile:
    dest=/etc/tendrl/node-agent/node-agent.conf.yaml
    insertafter='^tags:$'
    line="  - provisioner/ceph"
  when: "'usm_server' in group_names"

- name: Start and enable tendrl-node-agent daemon
  service:
    name=tendrl-node-agent
    state=started
    enabled=yes
