#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

# according to https://github.com/Tendrl/node-agent/blob/master/doc/source/installation.rst
- name: Specify etcd_connection in node-agent.conf.yaml
  lineinfile:
    dest=/etc/tendrl/node-agent/node-agent.conf.yaml
    regexp='^etcd_connection:*'
    line="etcd_connection{{ ':' }} {{ groups['usm_server'][0] }}"

- name: Start and enable tendrl-node-agent daemon
  service:
    name=tendrl-node-agent
    state=started
    enabled=yes
