---
- hosts: ceph_mon:ceph_osd
  remote_user: root
  tasks:
    - name: gather facts from Ceph nodes
      setup:

- name: Install ceph-ansible and install Ceph
  hosts: localhost
  connection: local
  roles:
    - ceph-ansible
