---
- hosts: ceph_mon
  remote_user: root
  tasks:
    - name: gather facts from Ceph Mon nodes
      setup:

- name: Install ceph-ansible and install Ceph
  hosts: localhost
  connection: local
  roles:
    - ceph-ansible
