---
# Perform auxiliary tasks after site.yml from tendrl-ansible.
# * prepare usm.yaml configuration for usmqe-tests

#
# Tendrl server
#

- hosts: tendrl_server
  remote_user: root
  tasks:
    - name: Read Tendrl admin password
      command: cat /root/password
      register: admin_password

    - debug: var=admin_password

    - name: Copy defaults.yaml template
      local_action: template src=./templates/defaults.yaml.j2 dest=./defaults.yaml

    - name: Copy usm.yaml template
      local_action: template src=./templates/usm.yaml.j2 dest=./usm.yaml

    - name: "WORKAROUND: update ansible (Tendrl/commons/issues/1054)"
      yum:
        name: ansible
        state: latest
      register: ansible_update_status

    - name: "WORKAROUND: (update ansible) restart tendrl-node-agent"
      service:
        name: "tendrl-node-agent"
        state: restarted
      when: ansible_update_status.changed
