---
# Perform following tasks, when applicable
# (e.g. there are nodes in gluster_servers group)
# * update and reboot all servers
# * Install Gluster nodes.
- include: qe_pre_installation_tasks.yml

- include: qe_reboot.yml

- include: test_setup.fips.yml
  when: configure_fips|default(false)|bool

- include: gluster.yml

- hosts: tendrl_server
  remote_user: root
  roles:
    - { role: epel, epel_enabled: 1 }
