---
# Perform following tasks, when applicable
# (e.g. there are nodes in gluster or ceph_* group)
# * Install Tendrl server.
# * Install Tendrl storage nodes.
# * Install Gluster nodes.
# * Configure gluster trusted storage pool and create bricks 
#   on all available devices on gluster nodes.
# * Install Ceph nodes.
# * Preconfigure ceph-ansible.
- include: qe_pre_installation_tasks.yml

- include: qe_reboot.yml

- include: tendrl_server.yml

- include: tendrl_node.yml

- include: gluster.yml
  when: groups.gluster is defined
- include: gluster_peers_bricks.yml
  when: groups.gluster is defined

- include: ceph_prereq.yml
  when: groups.ceph_osd is defined and groups.ceph_mon is defined

# workaround according to https://github.com/Tendrl/api/issues/86#issuecomment-285063914
# TODO: delete after resolving
- hosts: usm_nodes
  remote_user: root
  tasks:
    - name: Stop tendrl-node-agent daemon
      service:
        name=tendrl-node-agent
        state=stopped

    # immediate restart doesn't work
    - pause:
        seconds: 20
  
    - name: Start tendrl-node-agent daemon
      service:
        name=tendrl-node-agent
        state=started

# WORKAROUND for https://github.com/ceph/ceph-ansible/issues/1403
# TODO: delete after resolving
- hosts: ceph_osd
  remote_user: root
  tasks:
    - name: Run partprobe
      shell: partprobe || true
