---
# Perform following tasks, when applicable
# (e.g. there are nodes in gluster or ceph_* group)
# * Configure firewall
# * Install Tendrl server.
# * Install Tendrl storage nodes.
# * Install Gluster nodes.
# * Configure gluster trusted storage pool.
# * Install Ceph nodes.
# * Preconfigure ceph-ansible.
- include: qe_pre_installation_tasks.yml

# configure firewall
- include: firewall_tendrl.yml
- include: firewall_tendrl_workaround.yml

- include: qe_reboot.yml

- include: gluster.yml
  when: groups.gluster is defined
- include: gluster_peers.yml
  when: groups.gluster is defined

- include: ceph_prereq.yml
  when: groups.ceph_osd is defined and groups.ceph_mon is defined

- include: tendrl.yml

# WORKAROUND for https://github.com/ceph/ceph-ansible/issues/1403
# TODO: delete after resolving
- hosts: ceph_osd
  remote_user: root
  tasks:
    - name: Run partprobe
      shell: partprobe || true
