---
# Perform following tasks, when applicable
# (e.g. there are nodes in gluster or ceph_* group)
# * Configure firewall
# * Install Tendrl server.
# * Install Tendrl storage nodes.
# * Add Gluster repo.
# * Add Ceph repos.
- include: qe_pre_installation_tasks.yml

# configure firewall
- include: firewall_tendrl.yml
- include: firewall_tendrl_workaround.yml

- include: qe_reboot.yml

- include: tendrl.yml

# Add Centos Gluster YUM repo
- hosts: gluster
  remote_user: root
  roles:
    - gluster-centos-repo
    - gluster-gdeploy-copr

# Install centos-release-ceph package with Ceph Repos
- hosts: ceph_mon:ceph_osd
  remote_user: root
  roles:
    - ceph-centos-repo

# WORKAROUND for https://github.com/ceph/ceph-ansible/issues/1403
# TODO: delete after resolving
- hosts: ceph_osd
  remote_user: root
  tasks:
    - name: Run partprobe
      shell: partprobe || true
