---
#
# Configure firewall
#
- hosts: usm_server:usm_nodes
  remote_user: root
  pre_tasks:
    - name: install firewalld
      yum:
        name: 'firewalld'
        state: present

# TODO: firewall-tendrl-server role
#- name: Configure firewall on Tendrl server
#  hosts: usm_server
#  user: root
#  roles:
#    - { role: firewall-tendrl-server, when: groups.usm_server is defined }

# TODO: firewall-tendrl-node role
#- name: Configure firewall on Tendrl nodes
#  hosts: usm_nodes
#  user: root
#  roles:
#    - { role: firewall-tendrl-node, when: groups.usm_nodes is defined }

# TODO: firewall-gluster role
#- name: Configure firewall on Gluster nodes
#  hosts: gluster
#  user: root
#  roles:
#    - { role: firewall-gluster, when: groups.gluster is defined }

- name: Configure firewall on Ceph Monitor machines
  hosts: ceph_mon
  user: root
  roles:
   - { role: firewall-ceph-mon, when: groups.ceph_mon is defined }

- name: Configure firewall on Ceph OSD machines
  hosts: ceph_osd
  user: root
  roles:
    - { role: firewall-ceph-osd, when: groups.ceph_osd is defined }
