---
# WORKAROUND: firewall should not be disabled

- hosts: usm_server:usm_nodes
  remote_user: root
  tasks:
  - name: stop firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
    ignore_errors: yes
