---
# ansible-gluster libraries required
# https://github.com/dahorak/ansible-gluster.git or
# https://github.com/loadtheaccumulator/ansible-gluster.git
# export ANSIBLE_LIBRARY=../ansible-gluster/

- name: Gluster peer probe
  hosts: gluster
  remote_user: root
  vars:
    gluster_nodes: "{{groups['gluster']}}"

  tasks:

    - name: gluster peer probe
      glusterpeer: command=probe name="{{item}}"
      run_once: true
      with_items: "{{gluster_nodes[1:]}}"

    - name: gluster peer status
      glusterpeer: command=status
      run_once: true
