---

# This playbook tries to download configuration and log files related to Tendrl
# only instead of just downloading everything. This can be also useful when
# one needs to tweak the list further - copy this into new playbook and just
# comment out or add directories or files as you like.

- name: Download evidence available on all machines
  hosts: all
  user: root
  vars:
    evidence_dirs:
      - /var/log/audit/
      - /etc/yum.repos.d/
    evidence_files:
      - /var/log/messages
      - /var/log/yum.log
      - /var/log/boot.log
      - /proc/cpuinfo
      - /proc/meminfo
      - /proc/cmdline
      - /proc/version
      - /proc/devices
      - /proc/partitions
      - /etc/hosts
      - /etc/os-release
      - /etc/machine-id
  roles:
    - qe-evidence
    - qe-evidence-probe

- name: Download evidence from Tendrl server machine
  hosts: usm_server
  user: root
  vars:
    evidence_dirs:
      - /etc/tendrl/
      - /etc/httpd/
      - /etc/etcd/
      - /etc/carbon/
      - /etc/graphite-web/
      - /etc/ceph-installer/
      - /var/log/tendrl
      - /var/log/httpd/
      - /var/log/carbon/
      - /var/log/graphite-web/
      - /var/log/rabbitmq
    evidence_files:
      - /etc/collectd.conf
    evidence_journald_services:
      - tendrl-api
      - tendrl-performance-monitoring
      - ceph-installer
      - ceph-installer-celery
  roles:
    - qe-evidence
    - qe-evidence-probe-journald

- name: Download logs from Gluster Storage machines
  hosts: gluster
  user: root
  vars:
    evidence_dirs:
      - /etc/tendrl/
      - /etc/glusterfs/
      - /var/log/tendrl/
      - /var/log/glusterfs/
    evidence_journald_services:
      - tendrl-gluster-integration
      - tendrl-node-agent
      - tendrl-performance-monitoring
  roles:
    - qe-evidence
    - qe-evidence-probe-journald

- name: Download logs from Ceph Storage machines
  hosts: ceph
  user: root
  vars:
    evidence_dirs:
      - /etc/tendrl/
      - /etc/ceph/
      - /var/log/tendrl/
      - /var/log/ceph/
    evidence_journald_services:
      - tendrl-ceph-integration
      - tendrl-node-agent
      - tendrl-performance-monitoring
  roles:
   - qe-evidence
   - qe-evidence-probe-journald
