---
#
# Perform auxiliary tasks before installing Tendrl itself:
# * update all packages
# * enable ntp sync via chronyd
#
- hosts: usm_server:usm_nodes:usm_client
  remote_user: root
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      register: task_result
      until: task_result|success
      retries: 5
      delay: 5
    - name: Install chrony
      yum:
        name: chrony
        state: installed
    - name: Enable and start chronyd service
      service:
        name: chronyd
        state: started
        enabled: yes
