---
#
# Perform auxiliary tasks before installing Tendrl itself:
# * update all packages
#
- hosts: usm_server:usm_nodes
  remote_user: root
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
