---
#
# Perform auxiliary tasks before installing Tendrl itself:
# * update all packages
# * WORKAROUND: set selinux to permissive mode
#
- hosts: usm_server:usm_nodes
  remote_user: root
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: WORKAROUND configure selinux to permissive mode
      selinux:
        state: permissive
        policy: targeted
