---
#
# Reboot all machines (usm_server,usm_nodes,usm_client) and wait till they boot up
#
- name: Reboot all servers
  hosts: "usm_server:usm_nodes:usm_client"
  remote_user: root
  tasks:
    - name: Reboot
      shell: sleep 5 && reboot
      async: 1
      poll: 0
      when: not skip_reboot|default(false)|bool

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 10
        sleep: 10
        delay: 30
        timeout: 7200
      when: not skip_reboot|default(false)|bool
    - name: Ping
      ping:
      any_errors_fatal: True
