---

# This playbook configures jenkins slave machine, where usmqe integration
# tests are installed and executed.

- name: Configure QE server
  hosts: qe_server
  user: root
  roles:
   - epel
   - rh-python35
   - gluster-gdeploy-copr
   - qe-server
  tasks:
   - name: Add jenkins user into usmqe group
     user:
       name=jenkins
       groups=usmqe

- name: Prepare test environment of jenkins user
  hosts: qe_server
  user: root
  become: yes
  become_user: jenkins
  roles:
   - qe-server-user
