---

# This playbook configures qe server machine, where usmqe integration
# tests are installed and executed.

- name: Configure QE server
  hosts: qe_server
  user: root
  roles:
   - { role: epel, epel_enabled: 1 }
   - rh-python36
   - tendrl-ansible.gluster-gdeploy-copr
   - role: qe-ssl-ca
     when: skip_ssl_configuration is not defined
   - role: qe-ssl-cert
     ssl_key_perm: "0644"
     ssl_cert_name: "qeserver"
     when: skip_ssl_configuration is not defined
   - qe-server

- name: Prepare test environment of usmqe user
  hosts: qe_server
  user: root
  become: yes
  become_user: usmqe
  roles:
   - qe-server-user
