---

# This playbook configures qe server machine, where usmqe integration
# tests are installed and executed.

- name: Configure QE server
  hosts: qe_server
  user: root
  roles:
   - { role: epel, epel_enabled: 1 }
   - rh-python35
   - gluster-gdeploy-copr
   - qe-server

- name: Prepare test environment of usmqe user
  hosts: qe_server
  user: root
  become: yes
  become_user: usmqe
  roles:
   - qe-server-user
