---
#
# Install Tendrl server
#
- hosts: usm_server
  remote_user: root
  vars:
    install_from: packages
  roles:
    - etcd
    - tendrl-repo
    - ceph-installer-repo
    - { role: epel, epel_enabled: 1 } # based on https://github.com/Tendrl/tendrl-api/issues/25
    - tendrl-api
    - tendrl-node-agent
    - ceph-installer
    - tendrl-dashboard
    - tendrl-performance-monitoring
    - tendrl-alerting

  post_tasks:
    - debug: var=hostvars[groups['usm_server'][0]]['admin_password']
    - name: Copy usm.ini template
      local_action: template src=./templates/usm.ini.j2 dest=./usm.ini
      when: hostvars[groups['usm_server'][0]]['admin_password'].changed
