---
- hosts: usm_server 
  remote_user: root
  vars:
    install_from: packages
    enable_repo: epel
  roles:
    - etcd
    - epel # based on https://github.com/Tendrl/tendrl-api/issues/25
    - tendrl-repo
    - tendrl-api

- hosts: gluster
  remote_user: root
  vars:
    install_from: packages
    enable_repo: epel
  roles:
    - gluster-centos
    - tendrl-repo
    - tendrl-common
    - tendrl-node-agent
    - tendrl-gluster-integration

- include: gluster_peer_probe.yml
