---

#
# Install Tendrl server
#

- hosts: usm_server
  remote_user: root
  vars:
    etcd_ip_address: "{{ ansible_default_ipv4.address }}"
    tendrl_api_ip_address: "{{ etcd_ip_address }}"
  roles:
    - { role: epel, epel_enabled: 1 }
    - qe-tendrl-repo
    - ceph-installer # TODO: make it optional (when we don't deploy ceph)
    - tendrl-server
    - tendrl-performance-monitoring
  post_tasks:
    - debug: var=hostvars[groups['usm_server'][0]]['admin_password']
    - name: Copy usm.ini template
      local_action: template src=./templates/usm.ini.j2 dest=./usm.ini
      when: hostvars[groups['usm_server'][0]]['admin_password'].changed

#
# Install Tendrl storage node related stuff (not related to Ceph or Gluster).
#

- hosts: usm_nodes
  remote_user: root
  vars:
    etcd_ip_address: "{{ hostvars[groups['usm_server'][0]].ansible_default_ipv4.address }}"
  roles:
    - { role: epel, epel_enabled: 1 }
    - qe-tendrl-repo
    - tendrl-storage-node
