---
#
# Install Tendrl Ceph related stuff.
#
- hosts: ceph_mon:ceph_osd
  remote_user: root
  vars:
    install_from: packages
  roles:
    - { role: epel, epel_enabled: 1 } # based on https://github.com/Tendrl/node_agent/issues/75
    - tendrl-ceph-integration
