---
# Sets up machine so there can be performed Tendrl unit tests
# Installs all tendrl packages and pytest
- hosts: unittest_node
  remote_user: root
  roles:
    - { role: epel, epel_enabled: 1 }
    - qe-tendrl-repo
    - gluster-centos-repo
  post_tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Install pytest
      yum:
        name: 'pytest'
        state: latest
    - name: Install python-mock
      yum:
        name: 'python-mock'
        state: latest
    - name: "WORKAROUND - exclude=grafana-4.6.*"
      lineinfile:
        path: '/etc/yum.conf'
        line: 'exclude=grafana-4.6.*'
    - name: Install tendrl packages
      yum:
        name: 'tendrl*'
        state: latest
        exclude: 'tendrl-node-selinux tendrl-server-selinux'
