---
# Sets up machine so there can be performed Tendrl unit tests
# Installs all tendrl packages and pytest
- hosts: usm_test
  remote_user: root
  pre_tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: WORKAROUND configure selinux to permissive mode
      selinux:
        state: permissive
        policy: targeted
  roles:
    - { role: epel, epel_enabled: 1 }
    - qe-tendrl-repo
  post_tasks:
    - name: Install pytest
      pip:
        name: 'pytest'
    - name: Install tendrl packages
      yum:
        name: 'tendrl*'
        state: latest
