---
# Remove firewalld rule redirecting port 60080/tcp to port 10080/tcp (Graphite)
# used for access to Graphite from tests.

- hosts: tendrl_server
  remote_user: root
  tasks:
    - name: Remove redirection of port 60080/tcp to 10080/tcp (Graphite)
      firewalld:
        rich_rule: rule family={{ item }} forward-port port=60080 protocol=tcp to-port=10080
        zone: public
        permanent: yes
        immediate: yes
        state: disabled
      with_items:
        - ipv4
        - ipv6
