---
# Installation of helper tools which are needed for running automated tests
# cases from usmqe-tests.
# Note that even though this playbook enables EPEL repository only to install
# given tools, it can install other dependencies from EPEL during this process
# and so for this reason, teardown is not trivial.
- hosts: usm_nodes
  remote_user: root
  roles:
    - role: epel
  tasks:
    - name: Install tools required for usmqe-tests from EPEL
      yum:
        name: "{{ item }}"
        state: installed
        enablerepo: epel
      with_items:
        - stress-ng
      register: task_result
      until: task_result is success
      retries: 5
      delay: 5
