---
# ===========================================================================
#  QE configuration for stopping gluster volumes on gluster machines
# ===========================================================================
#
# This playbook serves as a setup for tests that check availability of
# gluster volumes.

- hosts: gluster_servers
  remote_user: root
  tasks:
    - name: Get list of gluster volumes
      command: gluster volume list
      run_once: true
      register: gluster_volumes
      changed_when: false

    - name: Stop all gluster volumes
      gluster_volume:
        state: stopped
        name: "{{ item }}"
      with_items: "{{ gluster_volumes.stdout_lines }}"
      run_once: true
      retries: 5
      delay: 5
      register: result
      until: 'result is success'
