---
# =============================================================
#  QE configuration for stopping tendrl node agent on one node
# =============================================================
#
# This playbook serves as a teardown for negative test cases, such as import
# with cluster in an invalid state.

- hosts: gluster_servers
  remote_user: root
  tasks:
    - name: Start tendrl-node-agent
      service:
        name: tendrl-node-agent
        state: started
