---
# ========================================
#  QE configuration for alerts logger
# ========================================
#
# This playbook serves as setup of alerts logger on tendrl server machine.
# It periodically logs alerts from tendrl api based on tendrl user.

- hosts: usm_server
  remote_user: root
  vars:
    tendrl_user: "admin"
    tendrl_password: "adminuser"

  tasks:
    - name: Create alerts_logger python script based on a template
      template:
        dest: /usr/local/bin/alerts_logger_{{ tendrl_user }}.py
        src: alerts_logger.py.j2
        force: yes
        mode: "+x"

    - name: Create service file based on a template
      template:
        dest: /etc/systemd/system/alerts_logger_{{ tendrl_user }}.service
        src: alerts_logger.service.j2
        force: yes

    - name: force systemd to reread configs
      systemd: daemon_reload=yes

    - name: enable alert logger
      systemd:
        name: alerts_logger_{{ tendrl_user }}
        state: started
        enabled: True
