---
# ========================================
#  QE configuration for alerts logger
# ========================================
#
# This playbook serves as setup of alerts logger on tendrl server machine.
# It periodically logs alerts from tendrl api based on tendrl user.

- hosts: usm_server
  remote_user: root
  vars:
    tendrl_user: "admin"
    tendrl_password: "adminuser"

  tasks:
    - name: Create alerts_logger python script
      copy:
        dest: /usr/local/bin/usmqe_alerts_logger.py
        src: usmqe_alerts_logger.py
        mode: "+x"

    - name: Create service file
      copy:
        dest: /etc/systemd/system/
        src: usmqe_alerts_logger@.service

    - name: force systemd to reread configs
      systemd: daemon_reload=yes

    - name: Add user to users.ini
      ini_file:
        path: /etc/usmqe_alerts_logger_users.ini
        section: "{{ tendrl_user }}"
        option: password
        value: "{{ tendrl_password }}"

    - name: Enable alert logger
      systemd:
        name: usmqe_alerts_logger@{{ tendrl_user }}
        state: started
        enabled: True
