#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

- name: Configure node monitoring
  lineinfile:
    dest=/etc/tendrl/node-monitoring/node-monitoring.conf.yaml
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: '^etcd_connection:*'
      line: "etcd_connection{{ ':' }} {{ groups['usm_server'][0] }}"
    - regexp: '^etcd_port:*'
      line: "etcd_port{{ ':' }} 2379"
      
- name: Start and enable tendrl-node-monitoring daemon
  service:
    name=tendrl-node-monitoring
    state=started
    enabled=yes
