---

- name: Check current ansible user account
  fail: msg="This role should not be run under root, but dedicated qe user!"
  when: ansible_user_id == 'root'

- name: Clone usmqe git repositories into home directory
  git:
    repo={{ item.repo }}
    dest={{ ansible_user_dir }}/{{ item.name }}
    version={{ item.version }}
    update=no
  with_items:
   - name: 'usmqe-setup'
     repo: "{{ usmqe_setup_repo }}"
     version: "{{ usmqe_setup_version }}"
   - name: 'usmqe-tests'
     repo: "{{ usmqe_tests_repo }}"
     version: "{{ usmqe_tests_version }}"
   - name: 'tendrl-ansible'
     repo: "{{ tendrl_ansible_repo }}"
     version: "{{ tendrl_ansible_version }}"

- name: HACK - install pylatest from PyPI via pip2
  shell: pip2 install --user pylatest

# Install all requirements of usmqe-tests repository via pip from PyPI
# locally for usmqe user and rh-python36 software collection only.
- name: HACK - install python modules required to run usmqe-tests
  shell: scl enable rh-python36 "pip install --user -r  {{ ansible_user_dir }}/usmqe-tests/requirements.txt"

# This is necessary for usmqe module and it's entry points (related to taretto
# selenium tests) to be available.
- name: HACK - install usmqe python module
  shell: scl enable rh-python36 "pip install --user -e {{ ansible_user_dir }}/usmqe-tests/"

# Based on http://developers.redhat.com/blog/2014/03/19/permanently-enable-a-software-collection/
- name: Enable the software collection in ~/.bashrc
  lineinfile:
    dest={{ ansible_user_dir }}/.bashrc
    state=present
    line="{{ item }}"
  with_items:
   - 'source /opt/rh/rh-python36/enable'
   - "export X_SCLS=$(scl enable rh-python36 'echo $X_SCLS')"

- name: Configure ssh - UserKnownHostsFile and StrictHostKeyChecking
  lineinfile:
    dest={{ ansible_user_dir }}/.ssh/config
    state=present
    create=yes
    line="{{ item }}"
  with_items:
    - 'Host *'
    - '  StrictHostKeyChecking no'
    - '  UserKnownHostsFile=/dev/null'
