---

- name: Add Gluster yum repository
  yum_repository:
    name: gluster-centos
    description: "{{ gluster_centos_repos[gluster_centos_repo].description }}"
    baseurl: "{{ gluster_centos_repos[gluster_centos_repo].baseurl }}"
    gpgcheck: no
    repo_gpgcheck: no
