---

# Based on section "2.4.1. Configuring Red Hat Storage Console Server Ports"
# from "Red Hat Storage Console 2.0 Quick Start Guide"

- name: Make sure firewalld is enabled and running
  service: name=firewalld state=started enabled=yes

- name: Enable port for Skyring (with https)
  firewalld:
    port=10443/tcp
    zone=public permanent=true state=enabled immediate=true
  when: skyring_uses_https

- name: Enable port for Skyring (without https)
  firewalld:
    port=8080/tcp
    zone=public permanent=true state=enabled immediate=true
  when: not skyring_uses_https

- name: Enable port for Salt-Master
  firewalld:
    port=4505-4506/tcp
    zone=public permanent=true state=enabled immediate=true

- name: Enable port for Graphite Web Access
  firewalld:
    port=10080/tcp
    zone=public permanent=true state=enabled immediate=true

- name: Enable port for Graphite Data
  firewalld:
    port=2003/tcp
    zone=public permanent=true state=enabled immediate=true

- name: Enable port for Ceph Installer
  firewalld:
    service=ceph-installer
    zone=public permanent=true state=enabled immediate=true

- name: Enable port for Redirections
  firewalld:
    port={{ item }}
    zone=public permanent=true state=enabled immediate=true
  with_items:
   - 443/tcp
   - 80/tcp
