---

#
# usmqe test user (the tests are executed under this account)
#

- name: Create usmqe unix user group
  group: name=usmqe state=present

- name: Create usmqe unix user account
  user:
    name=usmqe
    group=usmqe
    createhome=yes
    generate_ssh_key=yes
    comment="USM QE test user account"
    state=present

#
# ansible
#

- name: Install ansible
  yum: name=ansible state=present enablerepo=epel

- name: Configure ansible forks option
  lineinfile:
    regexp="^forks "
    line="forks          = 50"
    dest=/etc/ansible/ansible.cfg
    state=present

#
# usmqe dependencies
#

- name: Install usmqe dependencies from rh-python-35 collection
  yum: name={{ item }} state=installed
  with_items:
   - rh-python35-PyYAML
   - rh-python35-python-jinja2

#
# usmqeserver10 repo (from copr)
#

- name: Install usmqeserver10 repository
  copy:
    src='usmqe-usmqeserver10-epel-{{ ansible_distribution_major_version }}.repo'
    dest=/etc/yum.repos.d/

#
# other tools
#

- name: Install other useful tools
  yum: name={{ item }} state=installed enablerepo=epel
  with_items:
   - git
   - vim
   - tmux
   - htop
   - tree
