---

#
# usmqe test user (the tests are executed under this account)
#

- name: Create usmqe unix user group
  group: name=usmqe state=present

- name: Create usmqe unix user account
  user:
    name=usmqe
    group=usmqe
    createhome=yes
    generate_ssh_key=yes
    comment="USM QE test user account"
    state=present

- name: Allow usmqe group to do anything via sudo
  copy:
    src=20_usmqe_sudoers
    dest=/etc/sudoers.d/20_usmqe_sudoers
    mode=440
    owner=root
    group=root

#
# ansible
#

- name: Install ansible
  yum: name=ansible state=present enablerepo=epel

- name: Configure ansible forks option
  ini_file:
    dest=/etc/ansible/ansible.cfg
    section=defaults
    option=forks
    value=50

# Required to overcome ssh control path socket errors for very long hostnames.
- name: Configure ansible control_path
  ini_file:
    dest=/etc/ansible/ansible.cfg
    section=ssh_connection
    option=control_path
    value='%(directory)s/%%h-%%r'

#
# usmqe dependencies
#

- name: Install usmqe dependencies from rh-python-35 collection
  yum: name={{ item }} state=installed
  with_items:
   - rh-python35-PyYAML
   - rh-python35-python-jinja2

#
# support for web tests
#

- name: Install packages required for web tests
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - xorg-x11-server-Xvfb
    - x11vnc
    - firefox

- name: Install systemd service unit file
  copy:
    src={{ item }}
    dest=/etc/systemd/system/{{ item }}
    mode=0664
    owner=root
    group=root
    setype=systemd_unit_file_t
  with_items:
    - Xvfb.service
    - x11vnc.service

- name: Enable both services
  service:
    name={{ item }}
    enabled=true
  with_items:
    - Xvfb
    - x11vnc

- name: Start both services
  service:
    name={{ item }}
    state=started
  with_items:
    - Xvfb
    - x11vnc

- name: Open port for x11vnc server via firewalld
  firewalld:
    port=5900/tcp
    zone=public
    permanent=true
    state=enabled
    immediate=true
  ignore_errors: yes

#
# other tools
#

- name: Install other useful tools
  yum: name={{ item }} state=installed enablerepo=epel
  with_items:
   - git
   - vim
   - tmux
   - htop
   - tree
   - rpmlint
   - rpmdeplint
