#
# installation
#

- name: Install tendrl-api
  yum:
    name=tendrl-api
    state=latest
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Install tendrl-api-httpd
  yum:
    name=tendrl-api-httpd
    state=latest
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Install tendrl-api-doc
  yum:
    name=tendrl-api-doc
    state=latest
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

#
# post installation configuration
#

# as documented in README file
# TODO: this is prone to break sooner or later, but there is no yaml file
# module in ansible core or extras:
# https://github.com/ansible/ansible-modules-core/issues/1746
# fix of this hack would need to some external yaml module such as:
# https://github.com/kwoodson/yedit
- name: Configure etcd.yml - host
  replace:
    dest=/etc/tendrl/etcd.yml
    regexp="^  {{ ":" }}host{{ ":" }} .*"
    replace="  {{ ":" }}host{{ ":" }} \'{{ hostvars[groups['usm_server'][0]]['ansible_default_ipv4']['address'] }}\'"

# as documented in README file and deployment.adoc from Tendrl/documentation
- name: Start and enable tendrl-api
  service:
    name=tendrl-apid
    state=started
    enabled=yes

# as documented in README file and deployment.adoc from Tendrl/documentation
- name: Start and enable apache
  service:
    name=httpd
    state=started
    enabled=yes

#https://github.com/Tendrl/api/blob/master/docs/users.adoc#create-admin-user
- name: Load admin user to etcd
  shell: RACK_ENV=production rake etcd:load_admin
  args:
    chdir: /usr/share/tendrl-api
  register: rake_result
  changed_when: 
    - "'User named admin already exists.' not in rake_result.stdout"
  failed_when:
    - "rake_result.rc != 0"

- name: Extract admin password
  shell: echo "{{rake_result.stdout_lines[3] | regex_replace('^.*\"Password:\s*(.*)\".*$','\1')}}"
  register: admin_password
  when: rake_result.changed

- name: Store admin password to /root/password file
  copy:
    content="{{ admin_password.stdout }}\n"
    dest=/root/password
  when: admin_password.changed
