#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

# TODO: this is prone to break sooner or later, but there is no yaml file
# module in ansible core or extras:
# https://github.com/ansible/ansible-modules-core/issues/1746
# fix of this hack would need to some external yaml module such as:
# https://github.com/kwoodson/yedit
- name: Configure etcd.yml - host
  lineinfile:
    dest=/etc/tendrl/etcd.yml
    regexp="^  {{ ":" }}host{{ ":" }} \'127.0.0.1\'"
    line="  {{ ":" }}{{ item }}{{ ":" }} \'{{ hostvars[groups['usm_server'][0]]['ansible_eth0']['ipv4']['address'] }}\'"
  with_items:
    - host
    - host
    - host

- name: Start tendrl-api
  service:
    name=tendrl-apid
    state=started
