#
# installation
#

# TODO Add when packages are ready
#- name: Install tendrl-alerting
#  yum:
#    name=tendrl-alerting
#    state=latest

- fail: msg="There are no packages yet, we can't start and enable it"
  when: not ignore_incomplete_installation

#
# post installation configuration
#
