---
- name: Create directory for keys
  file: path="{{ ansible_env.HOME}}/ceph-ansible-keys" state=directory

- name: Copy ceph ansible files into different location so current user can change it
  shell: cp -R /usr/share/ceph-ansible/ {{ base_dir }}

- name: Copy sample files
  copy:
    src: "{{ base_dir }}/ceph-ansible/{{ item.src }}"
    dest: "{{ base_dir }}/ceph-ansible/{{ item.dst }}"
    remote_src: "True"
  with_items:
    - dst: "group_vars/all.yml"
      src: "group_vars/all.yml.sample"
    - dst: "group_vars/mons.yml"
      src: "group_vars/mons.yml.sample"
    - dst: "group_vars/osds.yml"
      src: "group_vars/osds.yml.sample"
    - dst: "site.yml"
      src: "site.yml.sample"

# edit all.yml file

- name: Set fetch directory
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#fetch_directory: fetch/"
    line: "fetch_directory: {{ ansible_env.HOME}}/ceph-ansible-keys"

- name: Change default Ceph cluster name
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: '^#cluster: ceph.*'
    line: 'cluster: test_name'

- name: Set automated fsid generation
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: '^#generate_fsid: true.*'
    line: 'generate_fsid: true'

# Disabled because this list is directly in ceph-ansible
#
#- name: Set package dependencies for CentOS
#  lineinfile:
#    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
#    regexp: '^#centos_package_dependencies:.*'
#    line: 'centos_package_dependencies:'
#  when: ansible_distribution == 'CentOS'
#
#- name: Set package dependencies for CentOS - packages
#  lineinfile:
#    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
#    insertafter: '^centos_package_dependencies:'
#    line: "  - {{ item }}"
#    regexp: "^centos_package_dependencies:\\\n.*  - {{ item }}"
#  with_items: ["libselinux-python", "python-setuptools", "ntp", "epel-release",
#              "yum-plugin-priorities.noarch", "hdparm", "python-pycurl"]
#  when: ansible_distribution == 'CentOS'
#
#- name: Set package dependencies for RHEL
#  lineinfile:
#    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
#    regexp: '^#redhat_package_dependencies:.*'
#    line: 'redhat_package_dependencies:'
#  when: ansible_distribution == 'RedHat'
#
#- name: Set package dependencies for RHEL - packages
#  lineinfile:
#    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
#    insertafter: '^redhat_package_dependencies:'
#    line: "  - {{ item }}"
#    regexp: "^redhat_package_dependencies:\\\n.*  - {{ item }}"
#  with_items: ["python-setuptools", "ntp", "hdparm", "python-pycurl"]
#  when: ansible_distribution == 'RedHat'


- name: Set Ceph origin 'distro' which means that repos are already set on nodes
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#ceph_origin: 'upstream'.*"
    line: "ceph_origin: 'distro'"

- name: Set client authentication
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#cephx: true.*"
    line: 'cephx: true'

- name: Set monitor interface to ansible_default_ipv4['interface']
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#monitor_interface: interface.*"
    line: "monitor_interface: {{ ansible_default_ipv4['interface'] }}"

- name: Set journal_size to 5 GB
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#journal_size: 0.*"
    line: 'journal_size: 5120'

- name: Set public_network to ansible_default_ipv4['address']/16
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/all.yml"
    regexp: "^#public_network: 0.0.0.0/0.*"
    line: "public_network: {{ ansible_default_ipv4['address'] }}/16"

# edit osds.yml file

- name: Uncomment devices
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: '^#devices:'
    line: 'devices:'
  when: "{{ devices }}"

- name: Add devices if they are set
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: "^  - /dev/{{item}}"
    insertafter: '^devices:'
    line: "  - /dev/{{item}}"
  with_items: "{{ devices }}"
  when: "{{ devices }}"

- name: Use device autodetection if devices are not set
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: "^#osd_auto_discovery: false"
    line: "osd_auto_discovery: true"
  when: "{{ not devices }}"

- name: Set collocation journals
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: "^#journal_collocation: false"
    line: "journal_collocation: true"
  when: "{{ collocation }}"

- name: Set raw_multi_journal when journals are not collocated
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: "^#raw_multi_journal: false"
    line: "raw_multi_journal: true"
  when: "{{ (not collocation) and journal_devices }}"

- name: Uncomment journal devices
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    regexp: '^#raw_journal_devices:'
    line: 'raw_journal_devices:'
  when: "{{ (not collocation) and journal_devices }}"

- name: Add devices for journals if they are set
  lineinfile:
    dest: "{{ base_dir }}/ceph-ansible/group_vars/osds.yml"
    insertafter: '^raw_journal_devices:'
    line: "  - /dev/{{item}}"
    regexp: "^raw_journal_devices:\\\n.*  - /dev/{{item}}"
  with_items: "{{ journal_devices }}"
  when: "{{ (not collocation) and journal_devices }}"

# see ceph-ansible requirements https://github.com/ceph/ceph-ansible/tree/master/roles/ceph-common#requirements
# As destination is /tmp/ansible.cfg by default because this configuration will not change
- name: Copy /usr/share/ceph-ansible/ansible.cfg to /tmp/ansible.cfg
  copy:
    src: "/usr/share/ceph-ansible/ansible.cfg"
    dest: "{{ ansible_conf }}"
    remote_src: "True"
