#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

- name: Start and enable tendrl-gluster-integration service
  service:
    name=tendrl-gluster-integration
    state=started
    enabled=yes
