---
dependencies:
  # make sure commons devel packages are installed for installation from sources
  - role: tendrl-devel
    when: install_from == "source"
  # for installation from packages, tendrl-commons should be installed
  # automatically based on rpm dependencies, but for installation from sources,
  # we need to install other tendrl components explicitly
  - role: tendrl-commons
    when: install_from == "source"
