- name: Install GlusterFS Server - CentOS
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-server
    - glusterfs-geo-replication
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5
  when: ansible_distribution == 'CentOS'

- name: Install GlusterFS Server - RedHat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - redhat-storage-server
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5
  when: ansible_distribution == 'RedHat'

- name: Run and enable glusterd service
  service:
    name=glusterd
    state=started
    enabled=yes
