# https://wiki.centos.org/HowTos/GlusterFSonCentOS
- name: Install GlusterFS Server - CentOS
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-server
    - glusterfs-geo-replication
  register: task_result
  until: task_result is success
  retries: 5
  delay: 5
  when: ansible_distribution == 'CentOS'

# https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html/installation_guide/installing_red_hat_storage_server_on_red_hat_enterprise_linux_layered_install
- name: Install GlusterFS Server - RedHat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - redhat-storage-server
  register: task_result
  until: task_result is success
  retries: 5
  delay: 5
  when: ansible_distribution == 'RedHat'

- name: Run and enable glusterd service
  service:
    name=glusterd
    state=started
    enabled=yes
