---
# Tendrl repo configuration selector
# might be "release" or "master"
tendrl_repo: "release"

## following variables overwrite general configuration selected by tendrl_repo
## URL to Tendrl main repo and gpg key
# tendrl_repo_url: ""
# tendrl_repo_gpgkey_url: ""
## URL to Tendrl dependencies repo and gpg key
# tendrl_dependencies_repo_url: ""
# tendrl_dependencies_repo_gpgkey_url: ""
