- name: Directory for git repository
  file:
    path="{{ tendrl_commons_repo }}"
    state=directory

- name: Clone git repository
  git:
    repo={{ tendrl_commons_repo_url }}
    version={{ tendrl_commons_repo_branch }}
    dest={{ tendrl_commons_repo }}

- name: Installation from source code
  pip:
    name=.
    chdir="{{ tendrl_commons_repo }}"

- name: Directory for Tendrl configuration
  file:
    path={{ item }}
    state=directory
  with_items:
    - /etc/tendrl
    - /etc/tendrl/node_agent
    - /etc/tendrl/ceph_integration
    - /etc/tendrl/gluster_integration

- name: Directory for Tendrl logs
  file:
    path={{ item }}
    state=directory
  with_items:
    - /var/log/tendrl
    - /var/log/tendrl/commons
    - /var/log/tendrl/node_agent
    - /var/log/tendrl/performance_monitoring
    - /var/log/tendrl/alerting
    - /var/log/tendrl/ceph_integration
    - /var/log/tendrl/gluster_integration
