---

# trc means "Tendrl Repo Configuration"
# configure Tendrl repos
trc:
  release:
    # URL to Tendrl main repo and gpg key
    tendrl_repo_url: "http://copr-be.cloud.fedoraproject.org/results/tendrl/release/epel-7-x86_64/"
    tendrl_repo_gpgkey_url: "https://copr-be.cloud.fedoraproject.org/results/tendrl/release/pubkey.gpg" 
    # URL to Tendrl dependencies repo and gpg key
    tendrl_dependencies_repo_url: "http://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/epel-7-x86_64/"
    tendrl_dependencies_repo_gpgkey_url: "https://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/pubkey.gpg"
  master:
    # URL to Tendrl main repo and gpg key
    tendrl_repo_url: "http://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/"
    tendrl_repo_gpgkey_url: "https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/pubkey.gpg" 
    # URL to Tendrl dependencies repo and gpg key
    tendrl_dependencies_repo_url: "http://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/epel-7-x86_64/"
    tendrl_dependencies_repo_gpgkey_url: "https://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/pubkey.gpg"
    
